### ISSUE TITLE
Null check problem with the function "getDotNotatedValue($array, $key)".

### ISSUE THREAD

**Issue by mdj613** [leafsphp/form#10]
When I try to validate data not present in the request() method, the validation function doesn't check if the value is null before trying to explode it.

{"credentials":{"username":null,"phone":null,"password":null}}<!DOCTYPE html><!--

TypeError: explode(): Argument leafsphp/leaf#2 ($string) must be of type string, int given in file C:\dev\leaf_projects\annonces_backend\vendor\leafs\form\src\Form.php on line 246
Stack trace:
  1. TypeError-&gt;() C:\dev\leaf_projects\annonces_backend\vendor\leafs\form\src\Form.php:246
  2. explode() C:\dev\leaf_projects\annonces_backend\vendor\leafs\form\src\Form.php:246
  3. Leaf\Form-&gt;getDotNotatedValue() C:\dev\leaf_projects\annonces_backend\vendor\leafs\form\src\Form.php:211
  4. Leaf\Form-&gt;validate() C:\dev\leaf_projects\annonces_backend\app\controllers\Auth\RegisterController.php:14
  5. App\Controllers\Auth\RegisterController-&gt;store() C:\dev\leaf_projects\annonces_backend\vendor\leafs\router\src\Router\Core.php:550
  6. call_user_func_array() C:\dev\leaf_projects\annonces_backend\vendor\leafs\router\src\Router\Core.php:550
  7. Leaf\Router\Core-&gt;invoke() C:\dev\leaf_projects\annonces_backend\vendor\leafs\router\src\Router\Core.php:521
  8. Leaf\Router\Core-&gt;handle() C:\dev\leaf_projects\annonces_backend\vendor\leafs\router\src\Router\Core.php:466
  9. Leaf\Router\Core-&gt;run() C:\dev\leaf_projects\annonces_backend\vendor\leafs\leaf\src\App.php:382
 10. Leaf\App-&gt;run() C:\dev\leaf_projects\annonces_backend\vendor\leafs\mvc-core\src\Core.php:121
 11. Leaf\Core-&gt;runApplication() C:\dev\leaf_projects\annonces_backend\public\index.php:110
 12. require_once() C:\dev\leaf_projects\annonces_backend\index.php:28

**Comment by crosa7** [comment]
Thanks for reporting this issue, I will transfer it to the leafs/form repo as it is related to that

**Comment by crosa7** [comment]
Can you provide in the description the code to replicate this?
As I can only replicate this if I setup a rule where the key is an integer, having null values is not producing an error for me, so maybe I am not trying the correct case. Thanks

**Comment by mdj613** [comment]
[composer.json](https://github.com/leafsphp/form/files/13429560/composer.json)
The auth controller :
<?php

namespace App\Controllers\Auth;

use Leaf\Auth;
use Leaf\Form;

class RegisterController extends Controller
{
    public function store()
    {
        $credentials = request()->get(['username', 'phone', 'password']);
        
        $validation = Form::validate($credentials, [
            'optional|username|max:15',
            'required',
            'min:8'
        ]);

        if (!$validation)
            response()->exit(Form::errors());

        $user = auth()->register($credentials, [
            'username',
            'phone'
        ]);

        if (!$user)
            response()->exit(auth()->errors());

        response()->json($user);
    }
}

**Comment by crosa7** [comment]
Looks like you have an issue in your rules. The rules array should be a key => value array, where the key is your parameter name and the value are the rules, so for your case, to validate the username, it would look something like this: `Form::validate($credentials, ['username' => 'max:15|required|min:8']))`

**Comment by mdj613** [comment]
Yeah, you're right. Thanks a lot. Could you please update the docs for the last version (3.5.0). It seems like some part are outdated.
Thanks again.

**Comment by crosa7** [comment]
Will check it, thanks!
