### ISSUE TITLE
Add validation for multidimensional arrays

### ISSUE THREAD

**Issue by Rasalas** [leafsphp/form#8]
Hi,

in an API project, I tried to validate nested values - like the value of the following: `$data['name']['first']`:

```php
<?php

$data = [
  'name' => [
    'first' => 'Jane',
    'last' => 'Doe'
  ],
  'email' => 'example@example.com',
  'password' => 'password1234',
];
```

...which didn't work.  
I couldn't find anything in the documentation, tried the dot notation that I knew from Laravel  - didn't work.  
I looked at the source, found out it only works for one-dimensional arrays, and then just implemented it for myself.

with my change, this works:
```php
<?php

$data = [
  'name' => [
    'first' => 'Jane',
    'last' => 'Doe',
  ],
  'email' => 'example@example.com',
  'password' => 'password1234',
];

$success = form()->validate($data, [
  'name.first' => 'required',
  'name.last' => 'required',
  'email' => 'required|email',
  'password' => 'required|min:8'
]);

if ($success) {
  // do something
} else {
  // get errors
  $errors = form()->errors();
}
```

I've never created pull requests before (I basically work alone), I tried to follow the contribution guide, but I'm not 100% sure if I'm doing it correctly here, as I already had working code before writing this issue.

I'll create a pull request with my changes and I will try to link this issue to it.

The tests that I added, all PASS.  
(only something in Tests\arraytest, that didn't work before, fails).

The Contribution Guide tells me to "open a suggestion issue first with the `suggestion` or `feature request` tag". I can't find that here.

This is obviously only a suggested feature - so a `feature request` for now - maybe you'd want to implement it differently or I missed something.

I'd like some pointers ;)  
Thanks!

**Comment by mychidarko** [comment]
Hi @Rasalas thanks for the suggestion and the PR. This is a great idea, I'll look through it. Also the issue with `array()` has been fixed, I'll post an update on that

**Comment by mychidarko** [comment]
@Rasalas I'll publish this as an update soon
